version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"

  # Maintain dependencies for go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Onsi dependencies
      onsi-go:
        patterns:
          - github.com/onsi/*
      # Kubernetes and controller-runtime dependencies
      kubernetes-go:
        patterns:
          - k8s.io/*
          - sigs.k8s.io/controller-runtime
      # AWS dependencies
      aws:
        patterns:
          - github.com/aws/*

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
