version: "2"

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      # Increased from 150 because this operator contain a lot of boilerplate.
      threshold: 200
    gocyclo:
      # Increased from 30 because existing reconcile functions are complex.
      min-complexity: 40
    lll:
      line-length: 150
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    rules:
      # Exclude `lll` issues for long comments starting with `go:generate` or `+kubebuilder`.
      - source: ^\/\/\s(go:generate|\+kubebuilder)
        linters:
          - lll
      # Exclude dupl since controllers have a lot of boilerplate code, and exclude
      # dynamic and unwrapped errors issues in controllers since they will only be logged.
      - path: internal/controller/
        linters:
          - dupl
          - err113
          - wrapcheck
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - dupl
          - funlen
          - goconst
          - gocyclo
          - lll
          - mnd
          - varnamelen
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/quortex/kubestatic
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
