---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubestatic-quortex-io-v1alpha1-firewallrule
  failurePolicy: Fail
  name: vfirewallrule-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kubestatic.quortex.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewallrules
  sideEffects: None
