---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubestatic.fullname" . }}-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubestatic.quortex.io
    resources:
      - externalips
      - firewallrules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kubestatic.quortex.io
    resources:
      - externalips/finalizers
      - firewallrules/finalizers
    verbs:
      - update
  - apiGroups:
      - kubestatic.quortex.io
    resources:
      - externalips/status
      - firewallrules/status
    verbs:
      - get
      - patch
      - update
