# permissions for end users to view externalips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalip-viewer-role
rules:
- apiGroups:
  - kubestatic.quortex.io
  resources:
  - externalips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubestatic.quortex.io
  resources:
  - externalips/status
  verbs:
  - get
