# Default values for kubestatic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- The desired cloud provider (only AWS at the moment).
cloudProvider: aws

# -- The cluster ID to be used for the kubestatic deployment.
clusterId: ""

# -- The VPC ID of the instance kubestatic is deployed in.
vpcId: ""

# -- Prevent EIP deallocation on nodes auto-assigned ExternalIPs.
preventEIPDeallocation: false

# -- The minimum duration to wait between two reconciliations for the same node.
nodeMinReconciliationInterval: 10s

# -- The duration for which nodes are automatically reconciled.
nodeReconciliationRequeueInterval: 1m

aws:
  # -- the region in which the cluster resides.
  region: ""
  # -- the access key id of a user with necessary permissions.
  accessKeyID: ""
  # -- the secret access key of a user with necessary permissions.
  secretAccessKey: ""

manager:
  image:
    # -- kubestatic manager image repository.
    repository: eu.gcr.io/quortex-registry-public/kubestatic
    # -- kubestatic manager image tag.
    tag: ""
    # -- kubestatic manager image pull policy.
    pullPolicy: IfNotPresent

  # --  kubestatic manager container required resources.
  resources: {}

  # -- kubestatic manager container security contexts
  securityContext: {}

  # -- kubestatic manager additional arguments to the entrypoint.
  extraArgs: []

kubeRBACProxy:
  enabled: true
  image:
    # -- kube-rbac-proxy image repository.
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    # -- kube-rbac-proxy image tag.
    tag: v0.8.0
    # -- kube-rbac-proxy image pull policy.
    pullPolicy: IfNotPresent
  # --  kube-rbac-proxy container required resources.
  resources: {}

# -- Number of desired pods.
replicaCount: 1

# -- Security contexts to set for all containers of the pod.
podSecurityContext:
  {}
  # fsGroup: 2000

# --  A list of secrets used to pull containers images.
imagePullSecrets: []

# --  Helm's name computing override.
nameOverride: ""

# --  Helm's fullname computing override.
fullnameOverride: ""

# --  Annotations to be added to pods.
podAnnotations: {}

# --  Node labels for Kubestitute pod assignment.
nodeSelector: {}

# --  Node tolerations for Kubestitute scheduling to nodes with taints.
tolerations: []

# --  Affinity for Kubestitute pod assignment.
affinity: {}

serviceAccount:
  # -- Annotations added to the ServiceAccount.
  annotations: {}

serviceMonitor:
  # -- Create a prometheus operator ServiceMonitor.
  enabled: false
  # -- Labels added to the ServiceMonitor.
  additionalLabels: {}
  # -- Annotations added to the ServiceMonitor.
  annotations: {}
  # -- Override prometheus operator scrapping interval.
  interval: ""
  # -- Override prometheus operator scrapping timeout.
  scrapeTimeout: ""
  # -- Relabellings to apply to samples before scraping.
  relabelings: []

networkPolicy:
  # -- Whether to enable kubestatic network policy.
  enabled: false
  # -- Ingress rules to add to the network policy.
  extraIngress: []
  #    - ports:
  #        - protocol: TCP
  #          port: 8443
  #      from:
  #        - namespaceSelector:
  #            matchLabels:
  #              kubernetes.io/metadata.name: monitoring
  #          podSelector:
  #            matchLabels:
  #              app.kubernetes.io/name: prometheus
  #              operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
  # -- Egress rules to add to the network policy.
  extraEgress: []
